### ISSUE TITLE
TypeError: {class} object is not iterable

### ISSUE THREAD

**Issue by bbartley** [SynBioDex/pySBOL3#195]
This is a common error that users stumble over, and the error message is not intuitive.  I suggest two ways to help the user intuit what the actual issue is:
1.  Add an explicit type check for iterable
2. Change the error meassage to something like `TypeError: {property} requires one or more values packed in an iterable`.  This more clearly indicates to the user that the problem is related to the cardinality of the property, rather than an issue with the child object's class type

See https://github.com/SD2E/opil/issues/160

**Comment by tcmitchell** [comment]
The attribute name of the property (`allowed_time` in SD2E/opil#160) is not available when the error message would get generated, only the URI of the property. Here is an example of your requested error message using `Component.types`:

```python
>>> import sbol3
RDFLib Version: 5.0.0
>>> c = sbol3.Component('http://example.org/sbol3/c1', sbol3.SBO_DNA)
>>> c.types = sbol3.SBO_PROTEIN
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/tmitchel/Projects/sd2/pySBOL3/sbol3/object.py", line 25, in __setattr__
    self.__dict__[name].set(value)
  File "/Users/tmitchel/Projects/sd2/pySBOL3/sbol3/property_base.py", line 160, in set
    raise TypeError(msg)
TypeError: Property http://sbols.org/v3#type requires one or more values packed in an iterable
```

Is that what you're looking for?

**Comment by bbartley** [comment]
I think that is still preferable to the current error message.  However, it is in fact possible to get the actual Python attribute name (though not necessarily concise):
```
import sbol3
  
sbol3.set_homespace('http://nope.nope/')
c = sbol3.Component('c', sbol3.SBO_DNA)

# Get Property object just for demonstration purposes -- from scope of an actual
# Property object you'd want to refer to `self` 
self_property = c.__dict__['features']

# Demonstrate how you'd retrieve the property name from within the Property scope
self_name = None
for name, property in self_property.property_owner.__dict__.items():
    if property is self_property:
        self_name = name
print(f'Type Error: Something wrong with values in {self_name} property')
```

**Comment by tcmitchell** [comment]
Updated draft error message:

```python
>>> import sbol3
RDFLib Version: 5.0.0
>>> c = sbol3.Component('http://example.org/sbol3/c1', sbol3.SBO_DNA)
>>> c.types = sbol3.SBO_PROTEIN
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/tmitchel/Projects/sd2/pySBOL3/sbol3/object.py", line 25, in __setattr__
    self.__dict__[name].set(value)
  File "/Users/tmitchel/Projects/sd2/pySBOL3/sbol3/property_base.py", line 177, in set
    raise TypeError(msg)
TypeError: types requires one or more values packed in an iterable
```
